### ISSUE TITLE
Automatize installation process

### ISSUE THREAD

**Issue by paradadf** [Choum28/Recalbox-Clcd#4]
Building upon https://github.com/Choum28/Recalbox-Clcd/issues/3, it would be cool if the installation process could be automatize.
The user could just type something like `wget https://url_of_gist_with_instructions.com`
and get everything downloaded and setup. This could be done with a simple bash script.
Even changing the "PI STATION" name over a prompt can be done.

Steps I see would be to edit:
### Activate I2C inside recalbox
* mount -o remount, rw /
* /etc/modules.conf
* /boot/config.txt
* /boot/cmdline.txt
* reboot and run the script again but skip the first steps?
### Check I2C address
* mount -o remount, rw /
* find the I2C address
### Scripts installation
* Download all scripts to the right location
* Give them proper rights with chmod
* Enter your I2C address into I2C_LCD_driver.py
* reboot

**Comment by Choum28** [comment]
Hello,

As you already have great such automatic, perhaps it should be better to have one of our repositories updated / merged.
I have updated the script for latest version of recalbox some week ago.

**Comment by paradadf** [comment]
I didn‘t notice. I‘ll modify the script and make a PR on your repo.
